### PR TITLE
GraphQL-676: Test unsubscribe customer

### PR DESCRIPTION
**Pull request by rafaelstz**
As we talked @naydav I created the `testUnsubscribeCustomer` test case
https://github.com/magento/graphql-ce/issues/676

### CODE REVIEW

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5206](https://jira.corp.magento.com/browse/ENGCOM-5206) has been created to process this Pull Request

**Comment by lenaorobei** [comment]
@magento rul all tests

**Comment by lenaorobei** [comment]
@magento run all tests

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-5206](https://jira.corp.magento.com/browse/ENGCOM-5206) has been created to process this Pull Request

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=708) <br/>All committers have signed the CLA.

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5206](https://jira.corp.magento.com/browse/ENGCOM-5206) has been created to process this Pull Request

**Pull request merged**
