### PR TITLE
GraphQl-200: Product Compare

### PR DESCRIPTION
**Pull request by kisroman**
### Fixed Issues (if relevant)

1. https://github.com/magento/graphql-ce/issues/200

### CODE REVIEW

**Comment by naydav** [comment]
@kisroman 
Please, looks on failed travis tests
Thanks

**Comment by kisroman** [comment]
@naydav working on this.

**Comment by naydav** [comment]
Hi @kisroman,
Problem with builds is related to mistake in scheme declaration
```
@resolver (class: "Magento\\ProductCompareGraphQl\\Model\\Resolver\\addProductToCompareList")
```
Pay attention on class name.
Thanks

**Comment by naydav** [comment]
Hello @kisroman,,
We are going to include wishlist functionality in 2.3.3 release.
Could you merge last mainline and verify that code is actual
Thanks

**Comment by naydav** [comment]
@kisroman 
Need to split this PR into two, core part and graphql part.
Please, let me know are you going to continue with this ticket? 
Thanks

**Comment by kisroman** [comment]
https://github.com/magento/magento2/pull/23704

**Pull request merged**
