### PR TITLE
Shopping cart grand total and taxes coverage

### PR DESCRIPTION
**Pull request by rogyar**
### Description (*)
This PR introduces a possibility to view cart totals as well as taxes applied within scope of the current shopping cart

### Fixed Issues (if relevant)
1. #426: [Place order] Cart tax
2. #425: [Place order] Cart grand total

### Manual testing scenarios (*)
1. Configure taxes for products/zones/customer
2. Add a taxable product to the shopping cart
3. Assign shipping address (that corresponds a taxable zone) to the shopping cart
4. Use the following query to check the totals and taxes:

```graphql
{
  cart(cart_id: "$cart_id") {
    prices {
      grand_total {
        value,
        currency
      }
      subtotal_including_tax {
        value
        currency
      }
      subtotal_excluding_tax {
        value
        currency
      }
      subtotal_with_discount_excluding_tax {
        value
        currency
      }
      applied_taxes {
        label
        amount {
          value
          currency
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by rogyar** [comment]
Still working on minor fixes and tests coverage

**Comment by TomashKhamlai** [comment]
@rogyar, do you know anything about?
```
1 exception(s):
Exception #0 (BadMethodCallException): Missing required argument $msrpPriceCalculators of Magento\Msrp\Pricing\MsrpPriceCalculator.

Exception #0 (BadMethodCallException): Missing required argument $msrpPriceCalculators of Magento\Msrp\Pricing\MsrpPriceCalculator.
```
It looks like not connected with your pull request, however the defect was found on this branch.

**Comment by rogyar** [comment]
Hi @TomashKhamlai. Didn't get something like this. Please, try the recent version, I've merged the mainline commits to the current branch.
If you still experience this issue, please describe steps to reproduce, so I can figure out what goes wrong.
Thank you

**Comment by TomashKhamlai** [comment]
[magento2#22190](https://github.com/magento/magento2/issues/22190)

**Comment by TomashKhamlai** [comment]
Got this:
```graphql
{
   "data" : {
      "cart" : {
         "prices" : {
            "grand_total" : {
               "value" : 10.83,
               "currency" : "USD"
            },
            "subtotal_excluding_tax" : {
               "value" : 10,
               "currency" : "USD"
            },
            "subtotal_including_tax" : {
               "currency" : "USD",
               "value" : 10.83
            },
            "applied_taxes" : [
               {
                  "amount" : {
                     "value" : 0.83,
                     "currency" : "USD"
                  },
                  "label" : "US-CA-*-Rate 1"
               }
            ],
            "subtotal_with_discount_excluding_tax" : {
               "value" : 10,
               "currency" : "USD"
            }
         }
      }
   }
}
```
I am not sure but I it looks like value is cropped. I believe that value should have format {integer number}{localized decimal sign}{fraction according to currency}. Pay attention that some currency has 3 positions after decimal sign and if I not mistaken some of the currency do not have fraction. In USD the value should be:
`10.00`
in `subtotal_excluding_tax.value` and `subtotal_with_discount_excluding_tax.value`

**Comment by keharper** [comment]
Documented as part of https://github.com/magento/devdocs/pull/4502/

**Pull request merged**
