### PR TITLE
magento/graphql-ce#977: [Test coverage] Cover exceptions in AssignShippingAddressToCart, AssignBillingAddressToCart

### PR DESCRIPTION
**Pull request by atwixfirster**
### Fixed Issues (if relevant)

1. magento/graphql-ce#977: [Test coverage] Cover exceptions in AssignShippingAddressToCart, AssignBillingAddressToCart

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Please set address not from the address book (send address in mutation body, not `customer_address_id `) so we will test invalid input.
`customer_address_set_invalid_country_id.php` fisture should be removed.

**Comment by atwixfirster** [comment]
> Please set address not from the address book (send address in mutation body, not `customer_address_id `) so we will test invalid input.
> `customer_address_set_invalid_country_id.php` fisture should be removed.

Good suggestion!

**implemented**

Thank you, @lenaorobei

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6061](https://jira.corp.magento.com/browse/ENGCOM-6061) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by lenaorobei** [comment]
@atwixfirster please pull latest code from `2.3-develop` and resolve conflicts.

**Comment by atwixfirster** [comment]
> @atwixfirster please pull latest code from `2.3-develop` and resolve conflicts.

**done**, ma'am :)

**Review by lenaorobei — APPROVED** [review]

**Pull request merged**
