### PR TITLE
Fix Quote Schema inconsistency

### PR DESCRIPTION
**Pull request by osrecio**
Fix Quote Schema inconsistency

### Description (*)

1) `qty` should be renamed  `quantity`
2) Input `CartItemQuantityInput` should be renamed to `CartItemUpdateQuantityInput`
3) Input `CartItemInput` should be renamed to `CartItemQuantityInput`
4) `data: CartItemInput!` should be renamed to `quantity: CartItemQuantityInput!`

### Fixed Issues (if relevant)
1. magento/graphql-ce#631: Schema inconsistency of "Quantity / Qty" declaration

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=634) <br/>All committers have signed the CLA.

**Comment by naydav** [comment]
Hello @osrecio,

Thanks for PR, will start a review today! What about another ticket with the scheme fixes? these tickets have top priority due to coming release

**Comment by osrecio** [comment]
Hi @naydav , For sure, I want to help in this part. 

It's my "first time" with graphql-ce repo and I want to go step by step. 

I fixed the tests for this PR, actually I need setup correctly my env to work in right way and be able to launch the tests before creating a PR

**Comment by osrecio** [comment]
When the tests stop failing I will squash the commits in one or 2 more descriptive.

This Weekend I will setup my env to run the tests etc before create PR.

**Comment by naydav** [comment]
> When the tests stop failing I will squash the commits in one or 2 more descriptive.
> 
> This Weekend I will setup my env to run the tests etc before create PR.

Thanks. Welcome on board. If you will have some questions, please, ping me in the slack channel

**Comment by osrecio** [comment]
I ran my [own tests](https://travis-ci.org/osrecio/graphql-ce/builds/525844024) and are ok

**Review by paliarush — APPROVED** [review]

**Comment by keharper** [comment]
Documentation updated in https://github.com/magento/devdocs/pull/4502/

**Pull request merged**
