### PR TITLE
GraphQl-661: Test coverage of FedEx shipping method

### PR DESCRIPTION
**Pull request by atwixfirster**
**Issue:** https://github.com/magento/graphql-ce/issues/661

### Description (*)
To test FedEx on-line shipping carrier then you should create a sandbox account and configure FedEx shipping method on back-end side:
 
fedex

### Proposed solution (*)
Move all sandbox settings to `dev/tests/api-functional/config/config-global.php` config file (this file under git ignore so we can hide our sandbox settings from the 3rd eyes): 

```php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

return [
    'carriers' => [
        'usps' => [
            'userid' => '0:3:xxxxxxx1==',
            'password' => '0:3:xxxxxxx2==',
        ],
        'fedex' => [
            'account' => '0:3:yyyyyyyy0==',
            'meter_number' => '0:3:yyyyyyyy1==',
            'key' => '0:3:yyyyyyyy2=',
            'password' => '0:3:yyyyyyyy3=',
            'production_webservices_url' => 'https://wsbeta.fedex.com:443/web-services',
        ],
    ]
];
```

### CODE REVIEW

**Comment by atwixfirster** [comment]
@naydav , this PR is ready for your review.

Thank you!!

**Review by naydav — CHANGES_REQUESTED** [review]
@atwixfirster 
As we talk early, need to introduce some mock object instead of 'real caller' object
Our tests should not depend on external system

The best way is creating preference in GraphQLTestModule and replace real object on our internal mock object

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5285](https://jira.corp.magento.com/browse/ENGCOM-5285) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-5285](https://jira.corp.magento.com/browse/ENGCOM-5285) has been created to process this Pull Request
:eight_spoked_asterisk: @naydav, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-5285](https://jira.corp.magento.com/browse/ENGCOM-5285) has been created to process this Pull Request

**Pull request merged**
