### PR TITLE
GraphQl-143: [Checkout] Add bundled product to Cart

### PR DESCRIPTION
**Pull request by pmclain**
### Description (*)
* Mutation for adding bundled cart items
* Resolver for fetching bundled cart item information

### Fixed Issues (if relevant)
1. magento/graphql-ce#143: [Cart Operations] Add bundled product to Cart

### Manual testing scenarios (*)
1. Create empty quote
```graphql
mutation {
  createEmptyCart
}
```
2. Query for desired bundle product and options
```graphql
{
  products(filter: {sku: {eq: "little-bobby-bundles"}}) {
    items {
      sku
      ... on BundleProduct {
        price_view
        items {
          option_id
          position
          title
          type
          options {
            id
            can_change_quantity
            is_default
            label
            position
            price
            price_type
            product {
              id
              sku
            }
            qty
          }
        }
      }
    }
  }
}
```
3. Add bundled product to cart
```graphql
mutation addBundlesToCart($cartId: String!) {
  addBundleProductsToCart(input: {
    cart_id: $cartId, 
    cartItems: [
      {
        data: {
          sku: "little-bobby-bundles"
          qty: 1
        }
        bundle_options: [
          {
            id: 1
            quantity: 2
            value: ["2"]
          }
          {
            id: 2
            quantity: 1
            value: ["5", "7"]
          }
        ]
      }
    ]
  }) {
    cart {
      cart_id
      items {
        id
        qty
        product {
          sku
        }
        ... on BundleCartItem {
          bundle_options {
            id
            label
            type
            values {
              id
              label
              price
              quantity
            }
          }
        }
      }
    }
  }
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by TomashKhamlai** [comment]
Hi, @pmclain. It will be a long-comment).
I have performed some negative scenarios and definitely I found something interesting. It is either Magento Core bug or problem of this PR.
### Preconditions:
Have a Registered Customer to be able manipulate with a cart from Storefront and from GraphQL 

### Steps to reproduce:
1) Create Simple Product with enough Quantity, Weight > 0 and SKU: simple-product-1
2) Create Configurable Product among with its options by creating new attribute with Default Label at-001 and 2 options: option1 and option2, leave everything else to their defaults. Price: 9 and Qty: 1000
3) Create Virtual Product Tax Estimation with SKU virtual-product-tax-estimation, Price 40.00, Qty 100500 and everything else leave by default
4) Create Bundle product
	Name: Bundle Product 5
	SKU: bundle-product-5
	Dynamic SKU: Yes
	Price: 10
	Dynamic Weight: Yes
	BUNDLE OPTIONS:

	Ship Bundle Items: SEPARATELY

	Option Title: bundle-opt1
	Input Type: Dropdown
	Required: YES
	Is Default: TRUE, Name: Simple Product 1, SKU: simple-product-1, Price: 2.0000, Price Type: Fixed, Default Quantity: 1, User Defined: YES
	Is Default: False, Name: Configurable Product-option2, SKU: configurable-product-option2, Price: 3.0000, Price Type: Fixed, Default Quantity: 1, User Defined: No

	Option Title: bundle-opt2
	Input Type: Radio Buttons
	Required: NO
	Is Default: False, Name: Virtual Product Tax Estimation, SKU: virtual-product-tax-estimation, Price: 5.0000, Price Type: Fixed, Default Quantity: 2, User Defined: No

	CUSTOMIZABLE OPTIONS:
	Option Title: opt
	Option Type: Field
	Required: Yes
	Price: 1.00
	Price Type: Fixed
	SKU: sku-opt
	Max Characters: 5
5) Know your IDs! :)
In this step we want to get which bundle IDs we have and which values are valid for these IDs.
I prefer to add product with everything included and then just execute the `query cart`
6) Build `mutation addBundleProductsToCart` body but use INVALID VALUES, I don't mean random values. I took values from another bundle option...
```graphql
mutation addBundleAndShowProductLinksInfo(
  $hasBundles: Boolean = true
) {
  addBundleProductsToCart(
    input: {
      cart_id: "B3TXGWgZ3EqQXCSXRDvlYm38xTzo7MsH"
      cartItems: {
        bundle_options: {
          id: 18
          quantity: 2
          value: [
            "47"
          ]
        }
        customizable_options: [
          {
            id: 6
            value: "48"
          }
        ]
        data: {
          sku: "bundle-product-5"
          qty: 2
        }
      }
    }
  ) {
    cart {
      items {
        __typename
        qty
          @include(
            if: $hasBundles
          )
        ... on BundleCartItem {
          bundle_options {
            id
            label
            type
            values {
              id
              label
              price
              quantity
            }
          }
          customizable_options {
            id
            type
            values {
              id
              value
            }
          }
        }
        product {
          __typename
          sku
            @include(
              if: $hasBundles
            )
          ... on BundleProduct {
            product_links {
              __typename
              link_type
              linked_product_sku
              linked_product_type
            }
          }
        }
      }
    }
  }
}
```
7) Execute and read the response:
```graphql
{
  "data": {
    "addBundleProductsToCart": {
      "cart": {
        "items": [
          {
            "__typename": "BundleCartItem",
            "qty": 2,
            "bundle_options": [],
            "customizable_options": [
              {
                "id": 6,
                "type": "field",
                "values": [
                  {
                    "id": 120,
                    "value": "48"
                  }
                ]
              }
            ],
            "product": {
              "__typename": "BundleProduct",
              "sku": "bundle-product-5",
              "product_links": null
            }
          },
          {
            "__typename": "VirtualCartItem",
            "qty": 2,
            "product": {
              "__typename": "VirtualProduct",
              "sku": "virtual-product-tax-estimation"
            }
          }
        ]
      }
    }
  }
}
```
8) We already have one problem but lets continue. Open Storefront as Customer and click "View and Edit Cart"
image
9) Try to place order.

### Expected result:
Validation should work at steps 7) 8) or 9)

### Actual result:
Error message without `$data` provided:
```html
<div role="alert" class="message message-error error">
        <div data-ui-id="checkout-cart-validationmessages-message-error" data-bind="text: $data"></div>
    </div>
```

image

**Comment by galaoleksandr** [comment]
Hello. Cannot reproduce this. Got an error: 1 exception(s):
Exception #0 (GraphQL\Error\Error): Type "CartItemInput" not found in document.

**Comment by naydav** [comment]
Hello @pmclain ,
Sorry for the delay with the PR processing. This functionality will be one of the main focuses for the next release.
This ticket already included in backlog of 2.3.3 release
Thanks

**Comment by pmclain** [comment]
@naydav No worries. This needs a bit of updating to handle some the recent changes in the QuoteGraphQl schema anyway.

**Comment by vpodorozh** [comment]
@novikor @swnsma @XxXgeoXxX - please pick up this PR.
I do not have permission any more.
Thx!

**Comment by lenaorobei** [comment]
@pmclain please add `<module name="Magento_QuoteGraphQl"/>` to the `module.xml`.

**Comment by pmclain** [comment]
@TomashKhamlai Thanks for merging in the latest upstream code. This PR is no longer functional and I'm working on getting it back in order.

**Comment by TomashKhamlai** [comment]
Please fix the behavior. The actual result can be achieved by actions described in the test
```php
    /**
     * @magentoApiDataFixture Magento/Bundle/_files/quote_with_bundle_and_options.php
     * @expectedException \Exception
     * @expectedExceptionMessage Invalid state change requested orsome more descriptive message and check the result of placing order.
     */
    public function testCannotChangeSelectionQty()
    {
        $sku = 'bundle-product';
        $quantity = 3;
        $itemId = null;

        $this->quoteResource->load(
            $this->quote,
            'test_cart_with_bundle_and_options',
            'reserved_order_id'
        );

        $maskedQuoteId = $this->quoteIdToMaskedId->execute((int)$this->quote->getId());
        $product = $this->productRepository->get($sku);
        /** @var $typeInstance \Magento\Bundle\Model\Product\Type */
        $typeInstance = $product->getTypeInstance();
        $typeInstance->setStoreFilter($product->getStoreId(), $product);
        /** @var $options \Magento\Bundle\Model\Option */
        $optionCollection = $typeInstance->getOptionsCollection($product);

        /** Find an option from fixture or find the first selection and change value for key selection_can_change_qty to 0 */
        foreach ($optionCollection as $option) {
            if ($option->getTitle() == "Option 3") {
                $selections = $typeInstance->getSelectionsCollection([$option->getId()], $product);
                /** @var $selection DataObject */
                /** @var  $selections Collection*/
                /** Find selection which has predefined qty and is not allowed for changing during checkout */
                foreach ($selections as $selection) {
                    if ($selection->hasData("selection_can_change_qty", "0")) {
                        $itemId = (int)$selection->getSelectionId();
                    }
                }
            }
        }

        /** The problem can be seen on orders page from admin after order placement. */
        $query = <<<QUERY
mutation {
  updateCartItems(
    input: {
      cart_id: "{$maskedQuoteId}"
      cart_items: {
        cart_item_id: $itemId
        quantity: $quantity
      }
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          sku
        }
      }
    }
  }
}

QUERY;
        $this->graphQlMutation($query);
```
We expect here some checks. These actions should be not allowed. And please rewrite the test, I wrote it only for the demonstration purpose.
I believe that the expected result for GraphQL should be similar to the result of the same action made by using the REST API. On Storefront the standard behavior is to recalculate.

**Comment by TomashKhamlai** [comment]
I used this bash snippet to get the proper response from the REST API, but change 
`rest="http://REPLACE/rest"` to your URL and replace `quote_id`, `option_id` and `item_id`.

```shell
#!/bin/bash
customer_token='';
rest="http://REPLACE/rest"

function getCustomerToken () {
    ### Accepts:
    ### - variable for token persistense (required for performance)
    ### - email of Customer (optional): John.Doe@example.com
    ### - password (optional): 123123qA
    local should_create_token=0;
    local token='';
    local body='';

    # Checks if argument was provided
    if [[ -z "$1" ]]; then
        should_create_token=1;
    else
        token="$1";
    fi

    # Checks if argument is token
    if [[ "${#token}" -ne 32 ]]; then
        should_create_token=1;
    fi

    if [[ -z "$2" ]]; then
        email='John.Doe@example.com';
    else
        email="$2"
    fi

    if [[ -z "$3" ]]; then
        password='123123qA';
    else
        password="$3"
    fi

    # Optimization
    if [[ $should_create_token -eq 1 ]]; then

        read -r -d '' body << BODY
{
    "username": "$email",
    "password": "$password"
}
BODY

        customer_token=$(curl -X POST "$rest/V1/integration/customer/token" \
        -H "Content-Type: application/json" \
        -d "$body");

        echo $customer_token && customer_token=$(echo $customer_token | tr -d '"');
    fi
}

function updateCartRest () {
    getCustomerToken $customer_token;
    local body='';

    read -r -d '' body << BODY
{
  "quote": {
    "items": [
      {
        "item_id": 3,
        "qty": 2,
        "quote_id": "1"
      }
    ]
  }
}
BODY

result=$(curl -X PUT "$rest/V1/carts/mine" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $customer_token" \
    -d "$body" | json_pp);


echo "$result";
}

updateCartRest;
```

Try to replace the body from
```json
{
  "quote": {
    "items": [
      {
        "item_id": 3,
        "qty": 2,
        "quote_id": "1",
      }
    ]
  }
}
```
to
```json
{
  "quote": {
    "items": [
      {
        "item_id": 3,
        "qty": 2,
        "quote_id": "1",
        "product_option": {
          "extension_attributes": {
            "bundle_options": [
              {
                "option_id": 2,
                "option_qty": 5
              }
            ]
          }
        }
      }
    ]
  }
}
```

Got response:
`"message" : "Invalid state change requested"` that could be a valid response or just my fault in snippet :)

**Comment by pmclain** [comment]
@TomashKhamlai In the current workflow child items shouldn't be directly updatable. The bundle item quantity can be updated, but this is proportional to the configuration in the current cart. Child cart items should not be visible in the cart response object, currently included in #699.

Changing the configuration on the storefront today currently redirects users from the cart page to `/checkout/cart/configure/id/{cartItemId}/product_id/{parentProductId}/`. We'll probably need to implement separate update mutations for updating configurable/group/bundle product configurations.

I have added validation preventing updating the QTY of not-visible quote items directly via the `updateCartItems`. Including the `cart_item_id` of any child cart item will now return an exception.

**Comment by TomashKhamlai** [comment]
@pmclain, could you check why we have different exceptions here? (requests are equal, only quantity differs)
**Request 1**
```graphql
mutation {
  updateCartItems(
    input: {
      cart_id: "QWUR2Kj1LchIXWAo3sHOsZ5rDRQ0Ffq8"
      cart_items: {
        cart_item_id: 18
        quantity: 2
      }
    }
  ) {
    cart {
      email
      items {
        id
        quantity
        product {
          sku
        }
      }
    }
  }
}
```
**Response1**
```graphql
{
  "errors": [
    {
      "message": "Could not find cart item with id: 18.",
      "category": "graphql-no-such-entity",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateCartItems"
      ]
    }
  ],
  "data": {
    "updateCartItems": null
  }
}
```

**Request 2**
```graphql
mutation {
  updateCartItems(
    input: {
      cart_id: "QWUR2Kj1LchIXWAo3sHOsZ5rDRQ0Ffq8"
      cart_items: {
        cart_item_id: 18
        quantity: 0
      }
    }
  ) {
    cart {
      email
      items {
        id
        quantity
        product {
          sku
        }
      }
    }
  }
}
```
**Response 2**
```graphql
{
  "errors": [
    {
      "message": "The 5 Cart doesn't contain the 18 item.",
      "category": "graphql-no-such-entity",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateCartItems"
      ]
    }
  ],
  "data": {
    "updateCartItems": null
  }
}
```

**Comment by TomashKhamlai** [comment]
`cart_item_id: 18` it is an id of the Bundle Product and the quantity is not updatable anymore.

please check:
```graphql
{
  "data": {
    "cart": {
      "billing_address": {
        "country": {
          "code": null,
          "label": null
        }
      },
      "shipping_addresses": [
        {
          "country": {
            "code": null,
            "label": null
          }
        }
      ],
      "items": [
        {
          "id": "18",
          "quantity": 1,
          "product": {
            "id": 14,
            "sku": "eb3-separately (bundle)",
            "attribute_set_id": 4
          }
        },
        {
          "id": "19",
          "quantity": 3,
          "product": {
            "id": 9,
            "sku": "virtual",
            "attribute_set_id": 4
          }
        },
        {
          "id": "20",
          "quantity": 2,
          "product": {
            "id": 4,
            "sku": "configurable-product-1-blue",
            "attribute_set_id": 9
          }
        }
      ]
    }
  }
}
```

**Comment by pmclain** [comment]
@TomashKhamlai Any chance you could share instructions for recreating that cart instance? I added some functional tests updating the bundle cart item quantity https://github.com/magento/graphql-ce/pull/396/commits/be264871ab9c90510e0552885b4e1e6eabfe361d. I wasn't able to triggers the errors reported unless the cart_item_id did not belong to the cart_id, so I'm now concerned the cart item ids in the cart response aren't accurate.

**Comment by TomashKhamlai** [comment]
You're right. Thank you.

**Comment by TomashKhamlai** [comment]
Found another problem.
#### Steps to reproduce:
1. Create `simple-product-1` and `simple-product-2` and set visibility as Not Visible Individually (it doesn't matter)
2. Start creating `b1-separately (bundle)` with 2 options (1 simple product per option). **image 1**
3. Open **Advanced Pricing** of this product
4. Set tier price for specific Group (choose `ALL_GROUPS` or `General`, both are suitable for the registered customer). Discount 20% if 5 products in the Cart **image 2**
5. Save the product.
6. Add product to the cart. To save some time you can add the product to cart from Storefront. It doesn't matter)
7. Update the Cart by using `updateCartItems`.
```graphql
mutation {
  updateCartItems(
    input: {
      cart_id: "7nwfj8TW9qxbBDoPalZ5bp40zMT4ikO6"
      cart_items: {
        cart_item_id: 10
        quantity: 5
      }
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          sku
        }
      }
      prices {      
        grand_total {
          value
          currency
        }
      }
    }
  }
}
```
8. Update quantity one more time. Set quantity to 1 or 5 again or some random number.
9. Place order from Storefront or using GraphQL 5 step placement procedure.
 - image 1 
image 1)
 - image 2
image 2

#### Expected result:
I can change the quantity of the bundle product

#### Actual result:
Some kind of magic
2019-07-24-19-57-gql-ce loc

**Comment by TomashKhamlai** [comment]
I was not able to reproduce similar behavior on Simple Product with discounts. @naydav, should I create a separate bug for this?

**Comment by pmclain** [comment]
@TomashKhamlai The cart items update resolver was saving the items/cart twice for each item passed in `cart_items[]`  during the request cycle. This caused the funky behaviour duplicating the child items.

**Comment by lenaorobei** [comment]
@pmclain could you please pull latest `2.3-develop` and verify the code is still relevant. We are going to proceed with this PR.

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5796](https://jira.corp.magento.com/browse/ENGCOM-5796) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by lenaorobei — APPROVED** [review]

**Pull request merged**
