### PR TITLE
Alphabetize Schema Fields#11

### PR DESCRIPTION
**Pull request by klimart**
Fixed: 

> The GraphQL fields should be alphabetized so that it's easier to find a specific field. Currently fields are not sorted so it's harder to find one on the list.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=104) <br/>All committers have signed the CLA.

**Comment by keharper** [comment]
Now that the fields are sorted alphabetically in a GraphQL browser, update the documentation so the fields are sorted there as well

**Comment by naydav** [comment]
Hi @klimart,
I would like to ask you to finish this PR
Of course, if that doesn't bother you
Thanks

**Comment by klimart** [comment]
Hi @naydav,
Seems all checks have been passed successfully.
Could you review the PR again?

**Comment by naydav** [comment]
@klimart Thanks
I will recheck

**Review by paliarush — APPROVED** [review]

**Pull request merged**
