### PR TITLE
graphQl-702 Added test coverage for Customer Downloadable Products

### PR DESCRIPTION
**Pull request by vovsky**
### Description (*)
This PR adds api-functional tests for Customer Downloadable Products functionality 

### Fixed Issues (if relevant)

1. magento/graphql-ce#702: [Test coverage] Customer Downloadable Products

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
@vovsky looks like redundant fixtures are used in some tests. Please consider revisiting these and addressing `WebAPI Tests build ` build failure. Thank you.

**Comment by vovsky** [comment]
@lenaorobei checks have passed now. Thanks

**Comment by lenaorobei** [comment]
@vovsky I meant slightly different thing and pushed it to your branch.

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5495](https://jira.corp.magento.com/browse/ENGCOM-5495) has been created to process this Pull Request

**Pull request merged**
