### PR TITLE
GraphQl-679: Add support of "Allow Guest Checkout" option

### PR DESCRIPTION
**Pull request by sinisa86**
https://github.com/magento/graphql-ce/issues/679

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=701) <br/>All committers have signed the CLA.

**Comment by TomashKhamlai** [comment]
@keharper, after this PR will be accepted the default the next behavior should be considered as expected.

#### Step 1. Navigate to Stores > Settings > Configuration > Sales > Checkout > Checkout Options > Allow Guest Checkout = No
#### Step 2. Create empty cart as a Guest
```graphql
mutation {
  createEmptyCart
}
```
#### Step 3. Add some product:
```graphql
mutation addSimpleToCart(
  $cart_id: String!
) {
  addSimpleProductsToCart(
    input: {
      cart_id: $cart_id
      cart_items: {
        data: {
          quantity: 1
          sku: "jacket-abbibass-1"
        }
      }
    }
  ) {
    cart {
      items {
        quantity
        ... on SimpleCartItem {
          product {
            name
          }
        }
      }
    }
  }
}
```
#### Step 4. Set guest email on Cart
```graphql
mutation setEmail(
  $cart_id: String!
  $email: String!
) {
  setGuestEmailOnCart(
    input: {
      cart_id: $cart_id
      email: $email
    }
  ) {
    cart {
      email
    }
  }
}
```

#### Expected result:
```graphql
{
  "errors": [
    {
      "message": "Guest checkout is not allowed.",
      "category": "graphql-authorization",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "setGuestEmailOnCart"
      ]
    }
  ],
  "data": {
    "setGuestEmailOnCart": null
  }
}
```
#release_notes

**Comment by TomashKhamlai** [comment]
@naydav currently it is impossible to transfer the Guest's Cart to Customer's Cart using GraphQL.
image

**Comment by TomashKhamlai** [comment]
According to my personal feeling of how it should work the expected behavior is:
When Unauthorized User tries to create a Guest Cart he gets a message that he is not eligible to create Cart. Probably extended with a tip to "Register a Customer Account or Login with existing one".

That is why I am failing this PR.

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-5290](https://jira.corp.magento.com/browse/ENGCOM-5290) has been created to process this Pull Request

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-5290](https://jira.corp.magento.com/browse/ENGCOM-5290) has been created to process this Pull Request

**Pull request merged**
