### PR TITLE
Improve graphql product pagination

### PR DESCRIPTION
**Pull request by Spaggel**
### Description

New PR as requested here: https://github.com/magento/magento2/pull/17953 

Fixed pagination exception which used to display the wrong number on error, used the total number of pages instead of the current one.

Added pagination information by returning the total pages, making it easier to render navigation using GraphQL.

### Fixed Issues (if relevant)
None

### Manual testing scenarios

1. Create GraphQL product query and query all the page_info fields, total_pages should be the number of pages available
```
page_info {
      page_size
      current_page
      total_pages
    }
```

2. Query products with a currentPage higher than the amount of available pages. You should get an exception message containing the requested page number and the total available pages

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=175) <br/>All committers have signed the CLA.

**Comment by naydav** [comment]
@Spaggel 
Pls check `Magento\GraphQl\Catalog\ProductSearchTest`

```

ProductSearchTest testQueryPageOutOfBoundException History | REST EE | < 1 sec
-- | -- | --
Magento\GraphQl\Catalog\ProductSearchTest::testQueryPageOutOfBoundException Failed asserting that exception message 'GraphQL response contains errors: currentPage value 2 specified is greater than the 1 page(s) available. ' contains 'GraphQL response contains errors: currentPage value 1 specified is greater than the number of pages available.'.
  | Failed | ProductSearchTest testSearchWithFilterWithPageSizeEqualTotalCount History | REST EE | < 1 sec
Magento\GraphQl\Catalog\ProductSearchTest::testSearchWithFilterWithPageSizeEqualTotalCount Failed asserting that exception message 'GraphQL response contains errors: currentPage value 2 specified is greater than the 1 page(s) available. ' contains 'GraphQL response contains errors: currentPage value 1 specified is greater than the number of pages available.'.
  | Failed | ProductSearchTest testFilterProductsInNextPageSortedByNameASC History | REST EE | < 1 sec
Magento\GraphQl\Catalog\ProductSearchTest::testFilterProductsInNextPageSortedByNameASC Exception: GraphQL response contains errors: currentPage value 2 specified is greater than the 1 page(s) available.   /opt/bamboo/builds/MCCE23-AT1227-RE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/Client.php:105 /opt/bamboo/builds/MCCE23-AT1227-RE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/Client.php:74 /opt/bamboo/builds/MCCE23-AT1227-RE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQlAbstract.php:49 /opt/bamboo/builds/MCCE23-AT1227-RE/build-1/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductSearchTest.php:613
  | Failed | ProductSearchTest testSearchWithFilterPageSizeLessThanCurrentPage History | REST EE | < 1 sec
Magento\GraphQl\Catalog\ProductSearchTest::testSearchWithFilterPageSizeLessThanCurrentPage Exception: GraphQL response contains errors: currentPage value 2 specified is greater than the 1 page(s) available.   /opt/bamboo/builds/MCCE23-AT1227-RE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/Client.php:105 /opt/bamboo/builds/MCCE23-AT1227-RE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/Client.php:74 /opt/bamboo/builds/MCCE23-AT1227-RE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQlAbstract.php:49 /opt/bamboo/builds/MCCE23-AT1227-RE/build-1/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductSearchTest.php:457
  | Failed | ProductSearchTest testQueryPageOutOfBoundException History | SOAP EE | < 1 sec
Magento\GraphQl\Catalog\ProductSearchTest::testQueryPageOutOfBoundException Failed asserting that exception message 'GraphQL response contains errors: currentPage value 2 specified is greater than the 1 page(s) available. ' contains 'GraphQL response contains errors: currentPage value 1 specified is greater than the number of pages available.'.
  | Failed | ProductSearchTest testSearchWithFilterWithPageSizeEqualTotalCount History | SOAP EE | < 1 sec
Magento\GraphQl\Catalog\ProductSearchTest::testSearchWithFilterWithPageSizeEqualTotalCount Failed asserting that exception message 'GraphQL response contains errors: currentPage value 2 specified is greater than the 1 page(s) available. ' contains 'GraphQL response contains errors: currentPage value 1 specified is greater than the number of pages available.'.
  | Failed | ProductSearchTest testFilterProductsInNextPageSortedByNameASC History | SOAP EE | < 1 sec
Magento\GraphQl\Catalog\ProductSearchTest::testFilterProductsInNextPageSortedByNameASC Exception: GraphQL response contains errors: currentPage value 2 specified is greater than the 1 page(s) available.   /opt/bamboo/builds/MCCE23-AT1227-SOE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/Client.php:105 /opt/bamboo/builds/MCCE23-AT1227-SOE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/Client.php:74 /opt/bamboo/builds/MCCE23-AT1227-SOE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQlAbstract.php:49 /opt/bamboo/builds/MCCE23-AT1227-SOE/build-1/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductSearchTest.php:613
  | Failed | ProductSearchTest testSearchWithFilterPageSizeLessThanCurrentPage History | SOAP EE | < 1 sec
Magento\GraphQl\Catalog\ProductSearchTest::testSearchWithFilterPageSizeLessThanCurrentPage Exception: GraphQL response contains errors: currentPage value 2 specified is greater than the 1 page(s) available.   /opt/bamboo/builds/MCCE23-AT1227-SOE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/Client.php:105 /opt/bamboo/builds/MCCE23-AT1227-SOE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/Client.php:74 /opt/bamboo/builds/MCCE23-AT1227-SOE/build-1/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQlAbstract.php:49 /opt/bamboo/builds/MCCE23-AT1227-SOE/build-1/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductSearchTest.php:457
```

**Review by paliarush — APPROVED** [review]

**Review by paliarush — APPROVED** [review]

**Review by TomashKhamlai — CHANGES_REQUESTED** [review]
Please add PHPDoc block
```
     * @param SearchFilter $searchFilter
     * @param Layer\DataProvider\Filters 
```

**Comment by Spaggel** [comment]
@paliarush @TomashKhamlai I'm gonna update this PR asap with the requested changes.

**Comment by naydav** [comment]
Unfortunately, we still have failed tests
```
ProductSearchTest testFilterProductsInNextPageSortedByNameASC 
ProductSearchTest testSearchWithFilterPageSizeLessThanCurrentPage
```

**Review by TomashKhamlai — APPROVED** [review]

**Comment by Spaggel** [comment]
@naydav I've noticed the failed tests but haven't had the time to look into them.. I'll try to update the PR ASAP

**Review by paliarush — APPROVED** [review]

**Comment by Spaggel** [comment]
Hi @naydav , I'm currently working on the failing tests and have a question:
in `app/code/Magento/CatalogGraphQl/Model/Resolver/Products.php`  in the resolve method there is a total count element, this seems to return the total amount of products matching the filters and NOT the total amount of products on the current page (in the GraphQL result). 
```php
$data = [
            'total_count' => $searchResult->getTotalCount(),
```

Is this intentional?  Because in the `testSearchWithFilterPageSizeLessThanCurrentPage` test there is this piece of code:
`$this->assertEquals(1, $response['products']['total_count']);`

But total_count is 3 when I run the tests. At this point, I'm not sure if my local tests are incorrect or the total_count should be 3.

**Comment by naydav** [comment]
@Spaggel Thanks for the information
I will recheck it.

**Comment by misha-kotov** [comment]
@Spaggel @naydav I don't see this test anymore: `testSearchWithFilterPageSizeLessThanCurrentPage`... did it get removed or renamed?

**Pull request merged**
