### PR TITLE
Use SVG badge

### PR DESCRIPTION
**Pull request by hugovk**
### Description

Use SVG Crowdin badge instead of PNG, for visual consistency with others.

Also add some missing fullstops, and because there's just one option under "Install Magento", there's no need to say "see either".

### Manual testing scenarios

1. Visit the README in the PR
2. Check the badge and text is improved

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [n/a] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### Before

image

### After

image

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=204) <br/>All committers have signed the CLA.

**Comment by naydav** [comment]
Hi @hugovk,
This repository is related to the GraphQL project
Could you close this PR and create a new one (from the same branch) to https://github.com/magento/magento2/pulls
Thanks

**Comment by hugovk** [comment]
@naydav Hi, I've already made a similar PR to https://github.com/magento/magento2/, please see https://github.com/magento/magento2/pull/18439.

Is it so that when that is merged, the README in this repo will also get updated? Thanks.

**Comment by naydav** [comment]
@hugovk,
Yes, after merging https://github.com/magento/magento2/pull/18439 this repo will be automatically updated
Thanks for the contribution!

**Pull request closed without merging**
