### PR TITLE
GraphQL-196 Added swatch data to the configurable product option values

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description (*)

PR for issue #196 Swatches: expose Hex color code and swatch images
Added swatch data in response, hex color, textual value or image path url.
Added Enum for swatch type [TEXTUAL, COLOR, IMAGE, EMPTY]

### Fixed Issues (if relevant)

1. #196: Swatches: expose Hex color code and swatch images.

### Manual testing scenarios (*)

Request: 
```
{
  products(filter: {sku: {eq: "conf"}}) {
    items {
      ... on ConfigurableProduct{    
      configurable_options{
          values {
            label
            swatch_data{
              type
              value
              thumbnail
            }
          } 
        }
      }
    }
  }
}
```
Response:
```
{
  "data": {
    "products": {
      "items": [
        {
          "configurable_options": [
            {
              "values": [
                {
                  "label": "red",
                  "swatch_data": {
                    "type": "COLOR",
                    "value": "#ff0000",
                    "thumbnail": null
                  }
                },
                {
                  "label": "black",
                  "swatch_data": {
                    "type": "IMAGE",
                    "value": ".../pub/media/attribute/swatch/swatch_image/30x20/b/_/b_1.png",
                    "thumbnail": ".../pub/media/attribute/swatch/swatch_thumb/110x90/b/_/b_1.png"
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by naydav** [comment]
Hello @sergiy-v,
What do you think about moving swatch functionality to a separate graphql module?

**Comment by naydav** [comment]
@TomashKhamlai, please, check this issue
Thanks

**Comment by lenaorobei** [comment]
@sergiy-v thank you for the contribution. Such kind of changes requires architecture review.

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-6494](https://jira.corp.magento.com/browse/ENGCOM-6494) has been created to process this Pull Request
:eight_spoked_asterisk: @naydav, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6494](https://jira.corp.magento.com/browse/ENGCOM-6494) has been created to process this Pull Request

**Pull request merged**
