### PR TITLE
Add total_quantity to cart response object

### PR DESCRIPTION
**Pull request by pmclain**
### Description (*)
Provide cart query property for the item summary count without requesting all cart items.

### Fixed Issues (if relevant)
1. magento/graphql-ce#827

### Manual testing scenarios (*)
1. Create empty cart
2. Add products to cart
3. Query cart requesting `total_quantity`
```graphql
{
  cart(cart_id: "{$maskedQuoteId}") {
    total_quantity
  }
}
```

`summary_count` should equal the sum of cart item quantities

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lenaorobei** [comment]
@paliarush please approve adding new schema field.

**Comment by paliarush** [comment]
@pmclain great feature, how about naming this `total_qty` or something similar?

**Comment by pmclain** [comment]
@paliarush Thanks for taking a look, I updated to `total_quantity`

**Comment by lenaorobei** [comment]
@magento run Functional Tests build

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5678](https://jira.corp.magento.com/browse/ENGCOM-5678) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5678](https://jira.corp.magento.com/browse/ENGCOM-5678) has been created to process this Pull Request

**Pull request merged**
