### PR TITLE
#486 added customer account validation in Quote operations

### PR DESCRIPTION
**Pull request by vovsky**
### Description
Added customer account validation in Quote operations. 
API functional tests have been added to \Magento\GraphQl\Quote\Customer\GetCartTest 

### Fixed Issues (if relevant)
1. magento/graphql-ce#486: Add customer account validation in Quote operations

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by TomashKhamlai** [comment]
Hi, @vovsky

Yesterday, before [event](https://github.com/magento/graphql-ce/pull/714#commits-pushed-0d24882) I noticed the problem that Customer can't get token after he was unlocked.

There are always chances that something went wrong on my side but please check this twice and share results in comments. I will retry testing and share more details on reproducing this case.

Cc: @lenaorobei

**Comment by vovsky** [comment]
@TomashKhamlai I have tried to unlock locked customer and perform quote operations. Please check method testGetCartForUnlockedCustomer in this temporary  PR https://github.com/magento/graphql-ce/pull/737/files . Is this what you mean? Thank you

**Comment by TomashKhamlai** [comment]
Hi, @vovsky, I am not able to do this for some period of time. Excuse me. Please contact with reviewers.

**Review by naydav — APPROVED** [review]

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-5295](https://jira.corp.magento.com/browse/ENGCOM-5295) has been created to process this Pull Request

**Pull request merged**
