### PR TITLE
GraphQl-167: Add support for '@magentoConfigFixture' annotation on API-functional tests

### PR DESCRIPTION
**Pull request by VitaliyBoyko**
### Description
Added support for '@magentoConfigFixture' annotation on GraphQL API-functional tests

### Fixed Issues (if relevant)
1. magento/graphql-ce#167: Add support for '@magentoConfigFixture' annotation on GraphQL API-functional tests

### CODE REVIEW

**Comment by naydav** [comment]
@VitaliyBoyko 
Please, check next tests

```
Magento\Test\Php\LiveCodeTest::testCodeStyle
PHP Code Sniffer detected 2 violation(s): 

FILE: ...nal/framework/Magento/TestFramework/Bootstrap/WebapiDocBlock.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 10 | ERROR | [x] Class is missing annotation block
 14 | ERROR | [x] Short description should not be in multi lines
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

WebAPI
```
Magento.Quote.Api.GuestShipmentEstimationTest.testEstimateByExtendedAddress
Magento.Quote.Api.GuestShipmentEstimationTest.testEstimateByExtendedAddress
Magento.Quote.Api.ShippingMethodManagementTest.testGetListForMyCart
```
Thanks

**Comment by naydav** [comment]
@VitaliyBoyko 
Have got Jenkins tests failure:
```
Magento\Quote\Api\GuestShipmentEstimationTest::testEstimateByExtendedAddress
Failed asserting that 2 matches expected 1.

/var/www/html/dev/tests/api-functional/testsuite/Magento/Quote/Api/GuestShipmentEstimationTest.php:103
```

```
Magento\Quote\Api\ShippingMethodManagementTest::testGetListForMyCart
Failed asserting that actual size 2 matches expected size 1.
```

**Comment by VitaliyBoyko** [comment]
Hey @naydav 
Can't reproduce this locally.
Is it possible to dump 'core_config_data' table, or get values from this table when the test on Jenkins being executed? I mean that certain moment when the test has started and all fixtures have been loaded.

**Comment by naydav** [comment]
@VitaliyBoyko 
Please, looks at fatal error from logs. It should be helpfull
thanks
```
PHP Fatal error:  Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@magentoApiConfigFixture" in method Magento\GraphQl\CatalogInventory\ProductOnlyXLeftInStockTest::testQueryProductOnlyXLeftInStockEnabled() was never imported. Did you maybe forget to add a "use" statement for this annotation? in /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
12:06:03 [WebAPI GRAPHQL-Tests-CE] Stack trace:
12:06:03 [WebAPI GRAPHQL-Tests-CE] #0 /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(727): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...')
12:06:03 [WebAPI GRAPHQL-Tests-CE] #1 /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(663): Doctrine\Common\Annotations\DocParser->Annotation()
12:06:03 [WebAPI GRAPHQL-Tests-CE] #2 /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(354): Doctrine\Common\Annotations\DocParser->Annotations()
12:06:03 [WebAPI GRAPHQL-Tests-CE] #3 /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(286):  in /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 54
```

**Comment by naydav** [comment]
@VitaliyBoyko 
Need to reuse `$subscribers[] = new \Magento\TestFramework\Annotation\ConfigFixture();` in `\Magento\TestFramework\Bootstrap\WebapiDocBlock`
The other changes should be reverted

**Comment by naydav** [comment]
@VitaliyBoyko I merged mainline and re-run build
Looks like we don't have problem with API-functional tests

But in the scope of this ticket need to remove all mentions and `TODOs` related to this issue
Would you like to do this in current PR?
Thanks

**Comment by lenaorobei** [comment]
@VitaliyBoyko I noticed one thing related to these changes - config values are not deleted after the test execution. Please address this issue. Thanks.

**Comment by lenaorobei** [comment]
@VitaliyBoyko thank you. I tested config values and they are removed after the test execution.
Could you please address static build issues and we will be able to proceed with this PR.

**Comment by VitaliyBoyko** [comment]
Hi @lenaorobei @naydav 
I've added the functionality to remove values from the DB and removed all TODO's. Thank you and sorry for the delay!

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-4151](https://jira.corp.magento.com/browse/ENGCOM-4151) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
