### PR TITLE
Implement customerCarts query

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
Ability to retrieve a list of active customer carts.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=946) <br/>All committers have signed the CLA.

**Comment by atwixfirster** [comment]
@karyna-tsymbal-atwix , please sign CLA in meantime ;)

Thanks

**Comment by lenaorobei** [comment]
@karyna-tsymbal-atwix thanks for your contribution. Unfortunately I need to move this PR to `on hold` until we will finalize product requirements with @nrkapoor. 

There is a chance that needed scenario with merge customer and guest carts will be covered with using `createEmptyCart` mutation and `cart ` query.

I'll keep you updated about any changes. Thanks for the understanding and patience.

**Comment by lenaorobei** [comment]
Sorry to say that but I need to close this PR due to requirement changes. The new flow we'll be working on:
Screen Shot 2019-10-14 at 9 25 11 AM

**Pull request closed without merging**
