### PR TITLE
magento/graphql-ce#: Add missed annotation blocks to Magento\GraphQl\Customer\CreateCustomerTest

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR adds missed annotation blocks to `Magento\GraphQl\Customer\CreateCustomerTest` + misspelling fix.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @atwixfirster. The use of `@inheritdoc` is in general discouraged. Please see the reference - https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc. For tiny cleanup fixes please combine into 1 PR. It should contain fixes for at leas all `Customer` tests. Thank you.

**Comment by atwixfirster** [comment]
> Hi @atwixfirster. The use of `@inheritdoc` is in general discouraged. Please see the reference - https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc. For tiny cleanup fixes please combine into 1 PR. It should contain fixes for at leas all `Customer` tests. Thank you.

@lenaorobei , I have updated the descriptions. Could you please verify? Thanks

**Comment by lenaorobei** [comment]
As per documentation: `A short description in case it adds meaningful information beyond the method name.` I believe that methods like `setUp` already have meaningful description, so additional info not needed.

**Comment by lenaorobei** [comment]
You can check for other typos in the `dev/tests/api-functional/testsuite/Magento/GraphQl/Customer` folder. Example: `testChangeSubscriptionStatuIfUserIsNotAuthorizedTest`.

**Comment by atwixfirster** [comment]
> You can check for other typos in the dev/tests/api-functional/testsuite/Magento/GraphQl/Customer folder. 

**done**

Thank you, @lenaorobei

**Comment by lenaorobei** [comment]
@magento run Database Compare

**Comment by lenaorobei** [comment]
@magento run Database Compare

**Comment by lenaorobei** [comment]
@magento run Database Compare

**Comment by lenaorobei** [comment]
@magento run Database Compare

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6245](https://jira.corp.magento.com/browse/ENGCOM-6245) has been created to process this Pull Request

**Pull request merged**
