### PR TITLE
GraphQl-299: Do not rely on global state in resolvers

### PR DESCRIPTION
**Pull request by rogyar**
### Description (*)
The store ID is added to the resolver context. So, the store ID can be retrieved from the context rather from the global state (store manager).

### Fixed Issues (if relevant)
1. #299: Do not rely on global state in resolvers

### CODE REVIEW

**Comment by naydav** [comment]
Postponed
Should be finished after the final decision about the proposal in
https://github.com/magento/graphql-ce/pull/490

**Comment by naydav** [comment]
@rogyar 
Please merge latest mainline and re-run travis
Thanks

**Comment by naydav** [comment]
Static tests failure:
```
agento\Test\Php\LiveCodeTest::testCodeMess
PHP Code Mess has found error(s):
/var/www/html/app/code/Magento/CustomerGraphQl/Model/Customer/UpdateCustomerAccount.php:19	The class UpdateCustomerAccount has a coupling between objects value of 13. Consider to reduce the number of dependencies under 13.
```

```
Magento\Test\Integrity\DependencyTest::testRedundant
Redundant dependencies found!

Module Magento\UrlRewriteGraphQl: hard [Magento\Store]

/var/www/html/dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php:492
```
@rogyar Could you check it?

**Comment by rogyar** [comment]
Sure, I will. Thank you

**Comment by naydav** [comment]
@rogyar please check static test failures
Thanks

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4819](https://jira.corp.magento.com/browse/ENGCOM-4819) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
