### PR TITLE
Links to the downloadable_product_samples are direct links

### PR DESCRIPTION
**Pull request by XxXgeoXxX**
### Description (*)
Original issue: https://github.com/magento/graphql-ce/issues/710

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by TomashKhamlai** [comment]
@XxXgeoXxX, I have restarted tests. Is this PR ready for testing?

**Comment by XxXgeoXxX** [comment]
Hi @TomashKhamlai 
Yes. Could you please check?

**Comment by TomashKhamlai** [comment]
Related #729. @XxXgeoXxX, can you take that task too?

**Comment by lenaorobei** [comment]
@XxXgeoXxX as per latest GraphQL syncup could you please introduce new field instead of changing the existing one? We need to take care of backward compatibility. The name can be `sample_file_url`.
Thank you.

**Comment by TomashKhamlai** [comment]
@naydav, after applying this fix, issue #729 will be still reproducible.
This fix is for downloadable_product_**samples**, but I believe that downloadable_product_**links** is also an issue.

**Comment by naydav** [comment]
@XxXgeoXxX, please check comment from @TomashKhamlai  
Thanks

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=719) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=719) before we can accept your contribution.<br/>**3** out of **17** committers have signed the CLA.<br/><br/>:white_check_mark: naydav<br/>:white_check_mark: lenaorobei<br/>:white_check_mark: pmclain<br/>:x: anthoula<br/>:x: davemacaulay<br/>:x: kabothu<br/>:x: vzabaznov<br/>:x: dhorytskyi<br/>:x: adifucan<br/>:x: joanhe<br/>:x: magento-engcom-team<br/>:x: okolesnyk<br/>:x: udovicic<br/>:x: viktym<br/>:x: sankalpshekhar<br/>:x: VeronikaYarats<br/>:x: deadlexus

**Comment by lenaorobei** [comment]
@akaplya please approve schema changes.

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-5373](https://jira.corp.magento.com/browse/ENGCOM-5373) has been created to process this Pull Request
:eight_spoked_asterisk: @naydav, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-5373](https://jira.corp.magento.com/browse/ENGCOM-5373) has been created to process this Pull Request
:eight_spoked_asterisk: @naydav, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
