### PR TITLE
[Checkout coverage] Added discount information to shopping cart

### PR DESCRIPTION
**Pull request by rogyar**
### Description (*)
This PR adds additional information about discount to the shopping cart details. The information contains discount amount and a label of the applied rule(s).

### Fixed Issues (if relevant)
1. #683 : Add discount information to cart

### Manual testing scenarios (*)
1. Create a shopping cart price rule
2. Add product to the shopping cart and use cart response for getting he information

```graphql
mutation {
  addSimpleProductsToCart(input: {
    cart_id:"X9KeOSMZuU10yww2S1A4DXfEwFpg0Q9X"
    cart_items: [
      {
        data: {
          quantity:1
          sku:"simle"
        }
      }
    ]
  })
  {
    cart {
      prices {
        discount {
          amount {
            value
            currency
          }
          label
        }
      }
    }
  }
}
```

or use cart query for an existing cart with a product and discount:

```graphql
{
  cart (cart_id:"X9KeOSMZuU10yww2S1A4DXfEwFpg0Q9X") {
    prices {
      discount {
        label
        amount {
          value
          currency
        }
      }
    }
  }
}
```

### CODE REVIEW

**Review by lenaorobei — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5181](https://jira.corp.magento.com/browse/ENGCOM-5181) has been created to process this Pull Request

**Comment by lenaorobei** [comment]
@rogyar as per latest GraphQL sync upplease consider changing `label` representation from comma-separated values to the array of values. Thank you.

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-5181](https://jira.corp.magento.com/browse/ENGCOM-5181) has been created to process this Pull Request

**Review by naydav — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @naydav, thank you for the review.
[ENGCOM-5181](https://jira.corp.magento.com/browse/ENGCOM-5181) has been created to process this Pull Request

**Pull request merged**
