### PR TITLE
GraphQl AddSimpleProductToCart is using the Magento core addProduct m…

### PR DESCRIPTION
**Pull request by pkodithuwakku**
…ethod in Magento\Quote\Model\Quote class. The items errors are returned as Magento\Framework\Exception\LocalizedException. In GraphQl these errors

needs to be converted in to a error class that inherits GraphQL\Error\ClientAware class in order to expose the correct error message. So Magento\Framework\GraphQl\Exception\GraphQlInputException
is used to for that conversion. Now the correct error messages are showing in Graphql results

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=359) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=359) before we can accept your contribution.<br/>

**Comment by TomashKhamlai** [comment]
@pkodithuwakku, please sign the CLA. Your have a working fix

**Comment by naydav** [comment]
Fix was merged in scope of
https://github.com/magento/graphql-ce/pull/368

**Comment by naydav** [comment]
Hi @pkodithuwakku,
Please, ping me in slack channel (@vnayda) if you would like to continue work with GraphQL
We started work on 2.3.2 release. There are a lot of tickets related to checkout workflow
Thanks

**Pull request closed without merging**
