### PR TITLE
Correct spelling

### PR DESCRIPTION
**Pull request by hugovk**
### Description

Correct spelling mistakes.

### Manual testing scenarios

1. Check tests pass with no regressions

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [n/a] All new or changed code is covered with unit/integration tests (if applicable)
 - [Pending] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by naydav** [comment]
Hi @hugovk,
This repository is related to the GraphQL project
Could you close this PR and create a new one (from the same branch) to https://github.com/magento/magento2/pulls
Thanks

**Comment by hugovk** [comment]
@naydav Thanks, will do. Which directories are unique to this project?

**Comment by naydav** [comment]
@hugovk,
There are not any unique directories. We have automatically sync-up between this repo and mainline.
The GraphQL repository is needed for more convenient processing of PR which are related to GraphQL track. 

Thanks for the contribution!

**Comment by naydav** [comment]
@hugovk,
BTW, If you want to get acquainted with the GraphQL  track, you can take any free task from https://github.com/magento/graphql-ce/issues
If you will have some question, please, ping me in Slack channel

**Pull request closed without merging**
