### PR TITLE
Issue #847 - [Wish List] Remove Wish List

### PR DESCRIPTION
**Pull request by Krielkip**
Adds removeWishlist to Graph Ql

### Description (*)
Adds the graph ql mutation to remove all items on the wishlist of current customer.

### Fixed Issues (if relevant)
1. magento/graphql-ce#847: [Wish List] Remove Wish List

### Manual testing scenarios (*)
1. Be logged in as customer
2. Have minimal 1 product in wishlist
3. use GraphQl code:
```
mutation {
  removeWishlist 
}
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lenaorobei** [comment]
Please note that schema for this mutation is still under the discussion https://github.com/magento/architecture/pull/326

This may cause some delays with PR processing.

**Comment by Krielkip** [comment]
Thanks for the replay. This issue was in the board of the Magento Live contribution Day in Amsterdam. Good to read that this schema is under discussion

**Comment by TomashKhamlai** [comment]
Checked test cases:

1. Remove Wish List with different types of products :heavy_check_mark:
2. Remove Wish List with OUT_OF_STOCK product :heavy_check_mark:
3. Remove Wish List twice :heavy_check_mark:

**Comment by TomashKhamlai** [comment]
Please, fix static tests.

**Comment by Krielkip** [comment]
I have added the folder /Test/Mtft with the Readme.md file. 
Still need to look how to do good static tests.

**Comment by TomashKhamlai** [comment]
There are some problems with the Storefront after removing the Wish List. Most likely it is a caching problem and not related to this PR. I am going to create an issue and then I will continue testing.

**Comment by lenaorobei** [comment]
Hi @Krielkip! Unfortunately we need to close this PR in order to not to increase tech debt with new storefront approach.
Hope you'll join us in upcoming project.

**Pull request closed without merging**
