### PR TITLE
Fixed changing cart item quantity using updateCartItems mutation

### PR DESCRIPTION
**Pull request by rogyar**
### Description (*)
This PR fixes updateCartItems behavior in terms of changing item quantity. It looks like after some refactoring we lost the saving operation upon changing item qty (without changing other item's data).

### Fixed Issues (if relevant)
1. #927 : Update quantity for updateCartItems mutation does not work

### Manual testing scenarios (*)
1. Create empty cart

```graphql
mutation {
  createEmptyCart
}
```

2. Add a simple product to the cart

```graphql
mutation {
  addSimpleProductsToCart(input: {
    cart_id: "$maskedCartId"
    cart_items: [
      {
        data: {
          quantity: 3,
          sku: "simple"
        }
      }
    ]
  }) {
    cart {
      items {
        id
        quantity
        product {
          name
        }
      }
    }
  }
}
```

3. Change the quantity of the added item using `updateCartItems` mutation

```graphql
mutation {
  updateCartItems(input: {
    cart_id:"$maskedCartId"
    cart_items: [
      {
        cart_item_id: $itemId
        quantity: 5
      }
    ]
  }) {
    cart {
      items {
        id
        quantity
        product {
          name
        }
      }
    }
  }
}
```

4. Retrieve the cart contents via separate query

```graphql
{
  cart(cart_id:"$maskedCartId") {
    items {
      id
      quantity
      product {
        name
      }
    }
  }
}
```

### CODE REVIEW

**Comment by lenaorobei** [comment]
@rogyar could you please cover this case with `api-functional` test?

**Comment by rogyar** [comment]
Sure, working on it

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5864](https://jira.corp.magento.com/browse/ENGCOM-5864) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by lenaorobei** [comment]
Unfortunately need to close because the issue was fixed by internal team in `2.3.3-develop` branch.

**Pull request closed without merging**
