### PR TITLE
Declare @doc and @resolver directives

### PR DESCRIPTION
**Pull request by Vinai**
### Description (*)

These declarations remove a lot of warnings from the PHPStorm GraphQl plugin while editing schema.graphqls files.

### References:

* https://graphql.github.io/graphql-spec/June2018/#sec-Type-System.Directives
* https://www.apollographql.com/docs/graphql-tools/schema-directives/

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Vinai** [comment]
Example screenshots without the declarations:

00-without-declarations

Example screenshots with the declarations:

01-with-declarations

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5460](https://jira.corp.magento.com/browse/ENGCOM-5460) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Vinai** [comment]
@lenaorobei I updated the PR despite your existing approval to add a declaration for the `@cache` directive, too. Please have another look if you still think it's okay - thank you.

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by Vinai** [comment]
@magento run all tests

**Comment by Vinai** [comment]
Seems like the builds is still stalled. Do you have an ETA when they will work again?
Will the stalled builds be restarted automatically, or should I take some action?

**Comment by lenaorobei** [comment]
@Vinai we are experiencing some issues with builds and working on the fix. I'll manually re-request builds run. Thanks for understanding and patience.

**Comment by Vinai** [comment]
Thank you @lenaorobei

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run Functional Tests build, WebAPI Tests build

**Comment by Vinai** [comment]
@lenaorobei The WebAPI Tests build seems to be (still?) hanging, it's been 17 hours.
Could you comment with the magic command again please?

**Comment by lenaorobei** [comment]
@magento run WebAPI Tests build

**Comment by lenaorobei** [comment]
@magento run WebAPI Tests build

**Pull request merged**
