### PR TITLE
Fixing category tree structure corruption issue in GraphQl

### PR DESCRIPTION
**Pull request by raivisdejus**
### Description (*)
Currently running the following Graph Ql query

```
{
    category(id: 2) {
        children {
            name
            children {
                name
                children {
                    name
                    children {
                        name
                    }
                }
            }
        }
    }
}
```

Will give categories that are sorted according to their levels where last items in a level get all the children.
```
Cat 1
Cat 2
- Cat 1 subcategory
- Cat 2 subcategory 
```

### Fixed Issues (if relevant)
1. magento/graphql-ce#246: Graph Ql category tree structure is lost (children all grouped with last item)

### Manual testing scenarios (*)
Run the following query with the fixed code
```
{
    category(id: 2) {
        children {
            name
            children {
                name
                children {
                    name
                    children {
                        name
                    }
                }
            }
        }
    }
}
```
Category tree structure is now preserved
```
Cat 1
- Cat 2 subcategory
Cat 2
- Cat 1 subcategory 
```

### Contribution checklist (*)
 - [+] Pull request has a meaningful description of its purpose
 - [+] All commits are accompanied by meaningful commit messages
 - [+] All new or changed code is covered with unit/integration tests (if applicable)
 - [+] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=257) <br/>All committers have signed the CLA.

**Comment by naydav** [comment]
@raivisdejus 
Pls, check GraphQL API-functional tests
https://travis-ci.com/magento/graphql-ce/jobs/159693711

**Comment by raivisdejus** [comment]
@naydav I have added sorting by position for the category tree retrieval and adjusted the tests to match the category structure defined for the tests [here](https://github.com/magento/graphql-ce/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Catalog/_files/categories.php)

Waiting for your further commetns

**Comment by nuzil** [comment]
Hello @raivisdejus 
This fix was also implemented in https://github.com/magento/graphql-ce/pull/164 and ready to merge

**Comment by raivisdejus** [comment]
@nuzil Thanks for the note :)

**Comment by raivisdejus** [comment]
Fixed in pr #164

**Pull request closed without merging**
