### PR TITLE
graphQl-812: test Add Variation From Another Configurable Product To Cart

### PR DESCRIPTION
**Pull request by VitaliyBoyko**
### Description (*)
Added adding a variation from another configurable product to cart test cases

### Fixed Issues (if relevant)
1. #812: [Test coverage] Add configurable product to cart using a variation that belongs to another configurable product

### CODE REVIEW

**Comment by lenaorobei** [comment]
When we are trying to add variation that does not belong to the parent product, exception should be thrown. You can create an issue if it does not work as expected and skip test with reference to this issue. Thanks.

**Comment by VitaliyBoyko** [comment]
Hi @lenaorobei 
> When we are trying to add variation that does not belong to the parent product, exception should be thrown. You can create an issue if it does not work as expected and skip test with reference to this issue. Thanks.

I believe there are 2 cases:
1.  When we are trying to add variation that does not belong to the parent product **and does not belong to common parents super attribute** - an exception should be thrown.
2.  When we are trying to add variation that does not belong to the parent product **and that belongs to common parents super attribute** - an exception should not be thrown.

The 2 test case are covered so far. So I should add the 1 test case, right?

**Comment by lenaorobei** [comment]
I mean that the case you added `testAddVariationFromAnotherConfigurableProductToCart` should fail and expect exception, but it does not.

**Comment by TomashKhamlai** [comment]
I agree with @lenaorobei. The configurable product should be added only when a simple product belongs to configurable. Here in the test, we see that it is possible to use `simple_10` and `simple_30` with `configurable_12345`, but only `simple_30` is a valid input. For `simple_10` we expect an exception.

Skipped tests with correct expectations and reference to the issue is a good idea.

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Please skip this specific case with the reference to https://github.com/magento/magento2 issue.
Thanks.

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-5912](https://jira.corp.magento.com/browse/ENGCOM-5912) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
