### PR TITLE
#32 CMS block coverage

### PR DESCRIPTION
**Pull request by roma-glushko**
### Description
This PR enables CMS block API for GraphQL. Since it's merged, it would be possible to retrieve CMS blocks by identifier from GraphQL and the following information will be available:
- CMS block identifier
- CMS block title
- CMS block content

### Fixed Issues (if relevant)
1. magento/graphql-ce#32: CMS block coverage

### CODE REVIEW

**Comment by nuzil** [comment]
What about Status of Block? Can we extend to receive it also?

**Comment by roma-glushko** [comment]
Hi @nuzil from the original requirements, the only enabled blocks can be retrieved by API. That's why status is not there. 

Can you please suggest a case when we need this? So we will be able to discuss that all together

**Comment by nuzil** [comment]
@roma-glushko in this case agree

**Comment by roma-glushko** [comment]
@nuzil however, I got the question. For the first iteration, there is no way to adjust list of available data to retrieve, but it will in further steps I guess. This is really something that we need to have here and everywhere in GraphQl API

**Pull request merged**
