### PR TITLE
[Test Coverage] Cover exceptions with tests.

### PR DESCRIPTION
**Pull request by usuyukiso**
Cover exceptions in  methods getEntityType and getAttributeCode with tests.
These methods can be only tested with Reflection.

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @usuyukiso! The idea of api-functional tests is to test real scenario, e.g. sending GraphQL query/mutation and compare data from fixtures with actual response. Please consider changing testing approach.

Could you also please add link to the issue, you are working on?

**Comment by usuyukiso** [comment]
Issue: https://github.com/magento/graphql-ce/issues/1010

**Comment by lenaorobei** [comment]
@usuyukiso please cover these cases with api-functional tests as per issue description.

**Comment by lenaorobei** [comment]
@usuyukiso closing this PR due to inactivity. 

Please feel free to create the new one to the https://github.com/magento/magento2 using api-functional tests as per issue description.

**Pull request closed without merging**
