### PR TITLE
[FEATURE] Added resolveRoute support (which is equal to Router for th…

### PR DESCRIPTION
**Pull request by lewisvoncken**
…e routerList implementation)

 - for example when you have a module which has a Router to the routerList it doesn't have url_rewrites but with the routeLocators it is possible to also route these url_keys

**This is a new PR according to
https://github.com/magento/graphql-ce/pull/939#issuecomment-533641652**

### Description (*)

I want to implement the customUrlLocator functionality for Mage2gen. I have taken a look at several blog modules and these even't implemented url_rewrites but a custom router.
https://github.com/krukas/Mage2Gen/pull/305

In the attachment there is an example module which has implemented the customUrlLocator.
[Mage2gen_BlogGraphQl.zip](https://github.com/magento/graphql-ce/files/3623589/Mage2gen_BlogGraphQl.zip)

image

image

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lenaorobei** [comment]
Hi @lewisvoncken,

Since your changes introduce new interfaces and add new fields to the schema it needs to be transparently reviewed and approved by architecture team in the https://github.com/magento/architecture repo.

Please submit PR with proposed changes in this repo first. Example: https://github.com/magento/architecture/pull/289

Thanks.

**Comment by lenaorobei** [comment]
Hi @lewisvoncken,

Did you had a chance to create architecture proposal?
Unfortunately we will not be able to move forward without it.

Thanks.

**Comment by lewisvoncken** [comment]
@zetlen can you confirm that this covers your feature request?

**Comment by lenaorobei** [comment]
As per discussion with @zetlen I will have to close this PR since it conflicts with architecture’s choices. Please feel free to open schema proposal in the architecture repo https://github.com/magento/architecture

**Pull request closed without merging**
