### PR TITLE
Filter error array by unique values

### PR DESCRIPTION
**Pull request by paul-stolk-webdiensten**
### Description (*)

Added an array_unique to prevent duplicate errors.

### Fixed Issues (if relevant)

1. https://github.com/magento/graphql-ce/issues/416: graphql-input provides to Customer as many errors as appeared instead of last one like on Magento Storefront #416

### Manual testing scenarios (*)

1. Create a product with two or more **required** customizable options
2. Add the product with GraphQl to the cart, with for example:

```
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "5qqnw42QYVX5SIHRFHETKhDQfb0mDe5K"
      cart_items: [
        {
          data: {
            quantity: 1
            sku: "416"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          sku
          stock_status
        }
        quantity
      }
    }
  }
}
```

### Contribution checklist (*)
 - [ x ] Pull request has a meaningful description of its purpose
 - [ x ] All commits are accompanied by meaningful commit messages
 - [ x ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ x ] All automated tests passed successfully (all builds are green)

Credits @seegrand

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
This check should be made on GraphQL level. Please use `GraphQlInputException`.
More info https://github.com/magento/graphql-ce/pull/1013

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6254](https://jira.corp.magento.com/browse/ENGCOM-6254) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@paul-stolk-webdiensten thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by TomashKhamlai** [comment]
Brilliant!

**Pull request merged**
