### PR TITLE
[Cart Operations] Update Cart Items Mutation

### PR DESCRIPTION
**Pull request by pmclain**
### Description (*)
Mutation for updating cart items.

https://github.com/magento/graphql-ce/issues/37

### Manual testing scenarios (*)
1. Create empty cart
```graphql
mutation {
  createEmptyCart
}
```
2. Add product to cart
```graphql
mutation AddToCart($cartId: String!) {
  addSimpleProductsToCart(input: {
    cart_id:$cartId
    cartItems:[
      {
        data: {
          sku:"product_dynamic_1",
          qty:2
        }
      }
      {
        data: {
          sku:"product_dynamic_2",
          qty:2
        }
      }
    ]
  }) {
    cart {
      cart_id
      items {
        id
        qty
        product {
          sku
        }
      }
    }
  }
}
```
3. Update cart items
```graphql
mutation updateCart($cartId:String!, $itemId:String!) {
  updateCartItems(input:{
    cart_id:$cartId
    cart_items:[
      {
        item_id:"$itemId"
        qty: 5
      }
    ]
  }) {
    cart {
      cart_id
      items {
        id
        qty
        product {
          sku
        }
      }
    }
  }
}
```
4. Validate item quantity has been updated
5. Remove cart item via zero qty update
```graphql
mutation updateCart($cartId:String!, $itemId:String!) {
  updateCartItems(input:{
    cart_id:$cartId
    cart_items:[
      {
        item_id:"$itemId"
        qty: 0
      }
    ]
  }) {
    cart {
      cart_id
      items {
        id
        qty
        product {
          sku
        }
      }
    }
  }
}
```
6. Validate cart item is removed

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by TomashKhamlai** [comment]
Similar problem like in #357 can be seen here while updating with qty = -1
Validation message is expected 
```
message: "Please enter a quantity greater than 0."
```

Do not think that it should be fixed here or now. Just linking issue to have use cases to check later
@naydav, can you approve that "zero qty update" is valid request?

**Comment by TomashKhamlai** [comment]
Covered [mc-8886](https://app.hiptest.com/l/scenario/2760735/mc-8886-update-shopping-cart-with-quote-bound-to-removed-customer-address)

**Comment by naydav** [comment]
> Similar problem like in #357 can be seen here while updating with qty = -1
> Validation message is expected
> 
> ```
> message: "Please enter a quantity greater than 0."
> ```
> Do not think that it should be fixed here or now. Just linking issue to have use cases to check later
> @naydav, can you approve that "zero qty update" is valid request?

Need to ask PO

**Comment by keharper** [comment]
Documented as part of https://github.com/magento/devdocs/pull/4502/

**Pull request merged**
