### PR TITLE
GraphQL-258: Product Layered Navigation filters return duplicates

### PR DESCRIPTION
**Pull request by vpodorozh**
magento/graphql-ce#258 Product Layered Navigation filters return duplicates

### Description (*)
 - added category_id_filter for catalog layer while filters retrieving

### Fixed Issues
1. magento/graphql-ce#258: Product Layered Navigation filters return duplicates
The `Filters` object returned by the Products query should contain the available layered navigation filters array. If the Products query is filtered by category id, that is analogous to the shopper browsing to a category page, so returned GraphQL product filters in layered nav should correspond to the filters shoppers see on the category page. 

### Preconditions (*)

1. Magento 2.3
2. Sample data

### Steps to reproduce (*)

Issue GraphQL query
```
{
  products(filter: {category_id: {eq: "28"}}) {
    total_count
    filters {
      name
      filter_items_count
      filter_items{
        label
        value_string
        items_count
      }
    }
  }
}
```
### Expected result (*)

Returned layered navigation filters are the same as what is shown on the category page, **for both search engine implementations: MySQL and ElasticSearch**
image

### Actual result (*)

1. Layered navigation filters contain duplicates and do not correspond to what is shown on the category page. 
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=268) <br/>All committers have signed the CLA.

**Comment by vpodorozh** [comment]
@magento-engcom-team give me test instance

**Comment by bchatard** [comment]
Hi @vpodorozh,

I'm also working on a fix for the layered navigation for this part. The category fix, is just a part of the fix, we also need to fix other filter.

For example, if you want to filter on "style_general" (after adding it into `ProductFilterInput` in `schema.graphqls`). Filters list contains incorrect items.

Frontend Layer:
layer_result

GraphQL query:
graphql_result

As you can see on screenshot, filter on "Material" are not the same between frontend layer and graphql...

I think Magento is working on it too because this part is mandatory for PWA

**Comment by bchatard** [comment]
BTW, the filters are not duplicated: There is some attributes with the name "Style": If you display "request_var", you will see different value.

**Comment by vpodorozh** [comment]
@bchatard - hi, thanks for the note about filtering.
About "duplications" - yes, you are right they are not duplicated, filters just have the same labels.

**Comment by vpodorozh** [comment]
@naydav - any update on it?
thx

**Review by paliarush — APPROVED** [review]
Changes look good. Requires PO approval and QA.

**Comment by naydav** [comment]
Hi @vpodorozh, could you merge last mainline and check that fix is still actual.
Thanks

@TomashKhamlai, please, verify this issue after mainline merging
Thanks

**Comment by vpodorozh** [comment]
> Hi @vpodorozh, could you merge last mainline and check that fix is still actual.
> Thanks
> 
> @TomashKhamlai, please, verify this issue after mainline merging
> Thanks

@naydav - done. Waiting for passed builds.

**Comment by vpodorozh** [comment]
@naydav @TomashKhamlai - any update on this?
thx!

**Comment by naydav** [comment]
Hi @vpodorozh,
Looks like we need call and some discussion.

Thanks

**Comment by TomashKhamlai** [comment]
@vpodorozh, there is a case when duplicates still occur.

Steps to reproduce:
```shell
### Replace to your URL, example: `endpoint="http://graphql-ce-sd.io/rest"`
endpoint="REPLACE/rest"

admin_token=$(curl -X POST "$endpoint/V1/integration/admin/token" \
  -H "Content-Type: application/json" \
  -d '{"username":"admin","password":"123123q"}') && echo $admin_token && admin_token=$(echo $admin_token | tr -d '"')

curl -X PUT "$endpoint/V1/products/WP02" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $admin_token" \
  -d '{"product":{"extension_attributes":{"category_links":[{"position":0,"category_id":"4"}]}}}' | json_pp

curl -X PUT "$endpoint/V1/products/WP05" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $admin_token" \
  -d '{"product":{"extension_attributes":{"category_links":[{"position":0,"category_id":"4"}]}}}' | json_pp
```

Send query:
```graphql
{
  products(filter: {category_id: {eq: "4"}}) {
    total_count
    filters {
      name
      filter_items_count
      filter_items{
        label
        value_string
        items_count
      }
    }
  }
}
```

**Actual result**
Style is duplicated
```graphql
{
  "data": {
    "products": {
      "total_count": 16,
      "filters": [
        {
          "name": "Style",
          "filter_items_count": 7,
          "filter_items": [
            {
              "label": "Backpack",
              "value_string": "24",
              "items_count": 4
            },
            {
              "label": "Luggage",
              "value_string": "25",
              "items_count": 1
            },
            {
              "label": "Duffel",
              "value_string": "26",
              "items_count": 2
            },
            {
              "label": "Messenger",
              "value_string": "27",
              "items_count": 4
            },
            {
              "label": "Laptop",
              "value_string": "28",
              "items_count": 6
            },
            {
              "label": "Exercise",
              "value_string": "29",
              "items_count": 6
            },
            {
              "label": "Tote",
              "value_string": "30",
              "items_count": 4
            }
          ]
        },
        {
          "name": "Style",
          "filter_items_count": 3,
          "filter_items": [
            {
              "label": "Leggings",
              "value_string": "109",
              "items_count": 1
            },
            {
              "label": "Sweatpants",
              "value_string": "113",
              "items_count": 2
            },
            {
              "label": "Track Pants",
              "value_string": "115",
              "items_count": 1
            }
          ]
        },
        {
          "name": "Size",
          "filter_items_count": 2,
          "filter_items": [
            {
              "label": "28",
              "value_string": "172",
              "items_count": 6
            },
            {
              "label": "29",
              "value_string": "173",
              "items_count": 6
            }
          ]
        },
...
```

**Comment by TomashKhamlai** [comment]
@vpodorozh, I appreciate the time and efforts that you have invested in order to fix this problem, but there is an idea of how to use your knowledge of this issue efficiently.

Generally, I believe that the issue is complex. Also, there is information that the core team has plans to introduce huge changes to catalog and sometimes it is too hard to merge a good solution after those changes. The idea is to cover the problem with effective API-functional test cases and skip it for now. Could you close this PR and open another one with coverage for this issue?
We will create an issue to unskip your tests and @naydav can set the "complex" label for that.

**Comment by vpodorozh** [comment]
@TomashKhamlai - no problem, I'll close this PR.
However, I do not have time to dive into this issue any more - could you please transfer it to somebody else?
Thx!

**Comment by TomashKhamlai** [comment]
@vpodorozh, yes probably I will try to cover this.

**Pull request closed without merging**
