### PR TITLE
Magento 2.3.2 - PWA - graphQl fetching Issue for phtml file called in static block #960

### PR DESCRIPTION
**Pull request by XxXgeoXxX**
### Description (*)
original issue: https://github.com/magento/graphql-ce/issues/960

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
`Magento\Widget\Model\Template\FilterEmulate` does not have `filter` method. It is called from `parent` class.

Please move the emulation logic to the `FilterEmulate` class, create the same method like for widget with area emulation.

**Comment by XxXgeoXxX** [comment]
> `Magento\Widget\Model\Template\FilterEmulate` does not have `filter` method. It is called from `parent` class.
> 
> Please move the emulation logic to the `FilterEmulate` class, create the same method like for widget with area emulation.

Done

**Comment by lenaorobei** [comment]
Please address failed builds.

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6164](https://jira.corp.magento.com/browse/ENGCOM-6164) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
