### PR TITLE
Extended CustomerOrders Query so it is possible to create a detail view including address, payment method, shipping method, totals and items

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
For our PWA studio client we needed an order detail view in the customer account. 

### Manual testing scenarios (*)
Example Query
`query customerOrders  {
    customerOrders {
        items {
            created_at
            grand_total
            id
            increment_id
            status
            shipping_amount
            discount_amount
            tax_amount
            sub_total
            items {
                name
                sku
                qty_ordered
                price_incl_tax
                row_total_incl_tax
                product_options {
                    attributes_info {
                        label
                        value
                    }
                }
            }
            shipping_address {
                firstname
            }
            billing_address {
                city
                street
            }
            shipping_description
            payment_method_title
        }
    }
}`

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=936) <br/>All committers have signed the CLA.

**Comment by lenaorobei** [comment]
Hi @dheesbeen. Thanks for your contribution, however we cannot accept this PR right away.

Schema is our API so any changes should be discussed and approved in https://github.com/magento/architecture repo.  I suggest creating a PR with proposed schema in this repo. Once it will be approved, we will be able to move forward with this PR.

**Comment by ghost** [comment]
@lenaorobei Thanks for the reply. @zetlen should be at our office today. I will try to discuss the PR for the architecture repo and check what he thinks.

**Comment by lenaorobei** [comment]
Hi @dheesbeen,

Please find architecture document here https://github.com/magento/architecture/pull/312/files
The proposal is still under the discussion and I encourage you to participate. Once it will be merged the schema must comply with it. I will be creating GitHub tickets here in the GraphQL once this PR is merged.
Unfortunately, we will have to close this PR in favor of approved schema, but I hope you'll pick some ticket given the fact that huge amount of work was already done in the scope of this PR.

Thank you.

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. 
@dheesbeen, please feel free to reopen it if you are planning to work on the schema https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/customer-orders.md

Please find related issues:
https://github.com/magento/graphql-ce/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+MyAccount+%3A%3A+Order+Details

**Pull request closed without merging**
